language: php
php:
  - 7.3

before_install:
  # turn off XDebug
  - phpenv config-rm xdebug.ini || return 0

install:
  - travis_retry composer install --no-progress --prefer-dist

script:
  - vendor/bin/phpstan analyze --level 5 -c phpstan.neon src --no-interaction --no-progress

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - tmp

